# Generated by Django 5.2 on 2025-06-05 01:39

import django.db.models.deletion
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Vehicle',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('make', models.CharField(max_length=32)),
                ('model', models.CharField(max_length=32)),
                ('type', models.CharField(choices=[('Sedan', 'Sedan'), ('SUV', 'SUV'), ('Van', 'Van')], max_length=8)),
                ('year', models.IntegerField()),
                ('trim', models.CharField(max_length=32)),
                ('fuel_type', models.CharField(choices=[('Regular', 'Regular'), ('Premium', 'Premium'), ('Diesel', 'Diesel')], max_length=8)),
                ('fuel_side', models.CharField(choices=[('Left', 'Left'), ('Right', 'Right')], max_length=5)),
                ('tank_capacity', models.FloatField()),
                ('mpg', models.FloatField()),
                ('current_miles', models.IntegerField()),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='vehicles', to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='RefuelLog',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('date', models.DateField()),
                ('gas_type', models.CharField(choices=[('Regular', 'Regular'), ('Premium', 'Premium'), ('Diesel', 'Diesel')], max_length=8)),
                ('gallons', models.FloatField()),
                ('cost', models.FloatField()),
                ('odometer', models.IntegerField()),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('vehicle', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='refuel_logs', to='garage.vehicle')),
            ],
        ),
    ]
