# Generated by Django 5.2 on 2025-05-04 07:42

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('register', '0001_initial'),
        ('stations', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Car',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('year', models.IntegerField()),
                ('make', models.CharField(max_length=32)),
                ('model', models.CharField(max_length=16)),
                ('mpg', models.FloatField()),
                ('tank_size', models.IntegerField(default=0)),
                ('fuel_type', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='stations.fuel')),
                ('owner', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='register.user')),
            ],
            options={
                'db_table': 'cars',
            },
        ),
    ]
