# Generated by Django 5.2 on 2025-05-22 04:38

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Station',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('overpass_id', models.BigIntegerField(unique=True)),
                ('name', models.CharField(blank=True, max_length=128, null=True)),
                ('lat', models.FloatField()),
                ('lon', models.FloatField()),
            ],
        ),
        migrations.CreateModel(
            name='GasPriceSubmission',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('regular', models.DecimalField(blank=True, decimal_places=2, max_digits=5, null=True)),
                ('premium', models.DecimalField(blank=True, decimal_places=2, max_digits=5, null=True)),
                ('diesel', models.DecimalField(blank=True, decimal_places=2, max_digits=5, null=True)),
                ('rating', models.PositiveSmallIntegerField(default=0)),
                ('submitted_at', models.DateTimeField(auto_now_add=True)),
                ('station', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='submissions', to='stations.station')),
            ],
        ),
    ]
