import type { Metadata } from "next";
import { Geist, Geist_Mono } from "next/font/google";
import "./globals.css";
import { IBM_Plex_Sans } from 'next/font/google'

const ibmPlex = IBM_Plex_Sans({
  subsets: ['latin'],
  weight: ['100','200','300','400','500','600','700'],
  variable: '--font-plex',
})

const geistSans = Geist({
  variable: "--font-geist-sans",
  subsets: ["latin"],
});

const geistMono = Geist_Mono({
  variable: "--font-geist-mono",
  subsets: ["latin"],
});

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en" className={`${geistSans.variable} ${geistMono.variable} ${ibmPlex.variable}`}>
      <body className="font-plex antialiased">
        {children}
      </body>
    </html>
  );
}
